from typing import Any, Dict, List, Literal, Optional, Protocol, Set

from fastauth.types import OAuthAccountData, RoleData, SessionData, TokenData, UserData


class UserAdapter(Protocol):
    async def create_user(
        self, email: str, hashed_password: Optional[str] = None, **kwargs
    ) -> UserData: ...

    async def get_user_by_id(self, user_id: str) -> Optional[UserData]: ...

    async def get_user_by_email(self, email: str) -> Optional[UserData]: ...

    async def update_user(self, user_id: str, **kwargs) -> UserData: ...

    async def delete_user(self, user_id: str, soft: bool = True) -> None: ...

    async def get_hashed_password(self, user_id: str) -> Optional[str]: ...

    async def set_hashed_password(self, user_id: str, hashed_password: str) -> None: ...


class SessionAdapter(Protocol):
    async def create_session(self, session: SessionData) -> SessionData: ...

    async def get_session(self, session_id: str) -> Optional[SessionData]: ...

    async def delete_session(self, session_id: str) -> None: ...

    async def delete_user_sessions(self, user_id: str) -> None: ...

    async def cleanup_expired(self) -> int: ...


class TokenAdapter(Protocol):
    async def create_token(self, token: TokenData) -> TokenData: ...

    async def get_token(self, token: str, token_type: str) -> Optional[TokenData]: ...

    async def delete_token(self, token: str) -> None: ...

    async def delete_user_tokens(
        self, user_id: str, token_type: str | None = None
    ) -> None: ...


class OAuthAccountAdapter(Protocol):
    async def create_oauth_account(
        self, account: OAuthAccountData
    ) -> OAuthAccountData: ...

    async def get_oauth_account(
        self, provider: str, provider_account_id: str
    ) -> Optional[OAuthAccountData]: ...

    async def get_user_oauth_accounts(self, user_id: str) -> List[OAuthAccountData]: ...

    async def delete_oauth_account(
        self, provider: str, provider_account_id: str
    ) -> None: ...


class RoleAdapter(Protocol):
    async def create_role(
        self, name: str, permissions: Optional[List[str]] = None
    ) -> RoleData: ...

    async def get_role(self, name: str) -> Optional[RoleData]: ...

    async def list_roles(self) -> list[RoleData]: ...

    async def delete_role(self, name: str) -> None: ...

    async def add_permissions(self, role_name: str, permissions: List[str]) -> None: ...

    async def remove_permissions(
        self, role_name: str, permissions: List[str]
    ) -> None: ...

    async def assign_role(self, user_id: str, role_name: str) -> None: ...

    async def revoke_role(self, user_id: str, role_name: str) -> None: ...

    async def get_user_roles(self, user_id: str) -> List[str]: ...

    async def get_user_permissions(self, user_id: str) -> Set[str]: ...


class AuthProvider(Protocol):
    id: str
    name: str
    auth_type: Literal["oauth", "credentials", "email"]


class OAuthProvider(AuthProvider):
    auth_type = "oauth"

    async def get_authorization_url(
        self, state: str, redirect_uri: str, **kwargs
    ) -> str: ...

    async def exchange_code(
        self, code: str, redirect_uri: str, **kwargs
    ) -> Dict[str, Any]: ...

    async def get_user_info(self, access_token: str) -> UserData: ...

    async def refresh_access_token(self, refresh_token: str) -> Optional[Dict]: ...


class CredentialsProvider(AuthProvider):
    type: Literal["credentials"] = "credentials"

    async def authenticate(self, credentials: Dict[str, Any]) -> Optional[UserData]: ...


class SessionStrategy(Protocol):
    async def create(self, user: UserData, **kwargs) -> str: ...

    async def validate(self, token: str) -> Optional[UserData]: ...

    async def invalidate(self, token: str) -> None: ...

    async def refresh(self, token: str) -> Optional[str]: ...


class SessionBackend(Protocol):
    async def read(self, session_id: str) -> Optional[Dict[str, Any]]: ...

    async def write(self, session_id: str, data: Dict[str, Any], ttl: int) -> None: ...

    async def delete(self, session_id: str) -> None: ...

    async def exists(self, session_id: str) -> bool: ...


class EmailTransport(Protocol):
    async def send(
        self, to: str, subject: str, body_html: str, body_text: Optional[str] = None
    ) -> None: ...


class EventHooks:
    async def on_signup(self, user: UserData) -> None: ...

    async def on_signin(self, user: UserData, provider: str) -> None: ...

    async def on_signout(self, user: UserData) -> None: ...

    async def on_token_refresh(self, user: UserData) -> None: ...

    async def on_email_verify(self, user: UserData) -> None: ...

    async def on_password_reset(self, user: UserData) -> None: ...

    async def on_oauth_link(self, user: UserData, provider: str) -> None: ...

    async def allow_signin(self, user: UserData, provider: str) -> bool: ...

    async def modify_session(
        self, session: Dict[str, Any], user: UserData
    ) -> Dict[str, Any]: ...

    async def modify_jwt(
        self, token: Dict[str, Any], user: UserData
    ) -> Dict[str, Any]: ...
